import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${inter.variable} flex min-h-screen flex-col items-center justify-center gap-48 py-12 px-6 font-sans`}
      >
        <div className="flex w-full max-w-md flex-col justify-between gap-6 text-sm md:flex-row lg:max-w-7xl">
          <p className="rounded-2xl border border-gray-300 bg-gray-100 p-4 text-center">
            Get started by editing{" "}
            <span className="font-bold">pages/index.tsx</span>
          </p>

          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center gap-2"
          >
            <span>By</span>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={100}
              height={24}
              priority
            />
          </a>
        </div>

        <div className="flex items-center justify-center gap-4">
          <Image
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />

          <Image
            src="/thirteen.svg"
            alt="Thirteen"
            width={40}
            height={31}
            priority
          />
        </div>

        <div className="grid grid-cols-1 gap-6 text-center md:grid-cols-2 lg:max-w-7xl lg:grid-cols-4">
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="block rounded-2xl border border-gray-300 bg-gray-100 py-4 px-10"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className="mb-2 font-semibold">Docs</h2>
            <p className="max-w-prose text-sm opacity-60">
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="block rounded-2xl border border-gray-300 bg-gray-100 py-4 px-10"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className="mb-2 font-semibold">Learn</h2>
            <p className="max-w-prose text-sm opacity-60">
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="block rounded-2xl border border-gray-300 bg-gray-100 py-4 px-10"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className="mb-2 font-semibold">Templates</h2>
            <p className="max-w-prose text-sm opacity-60">
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="block rounded-2xl border border-gray-300 bg-gray-100 py-4 px-10"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className="mb-2 font-semibold">Deploy</h2>
            <p className="max-w-prose text-sm opacity-60">
              Instantly deploy your Next.js site to a shareable URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
